name: Ubuntu
on:
  push:
    branches:
      - master
  pull_request:
env:
  targetName: danmaQ
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        qt_ver: [5.15.2]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          modules: 'qtcharts qtwebengine'
          cached: 'false'
      - name: ubuntu install
        run: sudo apt-get install -y libqt5x11extras5-dev cmake flatpak flatpak-builder
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build flatpak
        run: |
          flatpak install flathub org.kde.Sdk//5.15
          flatpak install flathub io.qt.qtwebengine.BaseApp//5.15
          flatpak-builder --repo=repo --force-clean build-dir org.tuna.danmaQ.local.json
          flatpak build-bundle repo danmaQ.flatpak org.tuna.danmaQ
        working-directory: flatpak
    # 上传artifacts          
      - uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: flatpak/danmaQ.flatpak
      # tag 上传Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: flatpak/danmaQ.flatpak
          asset_name: ${{ env.targetName }}
          tag: ${{ github.ref }}
          overwrite: true
